language: go
go:
- 1.5
before_install:
- go get github.com/golang/lint/golint
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover;
  fi
script:
- '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || $HOME/gopath/bin/goveralls -service=travis-ci
  -repotoken $COVERALLS_TOKEN'
- "$HOME/gopath/bin/golint ./..."
- go vet
- go test -v ./...
notifications:
  email:
    on_success: never
    on_failure: change
env:
  global:
    secure: YK0uwmQf7sZTKy2a798CImQb/nL21Oo7QAgjeJbtjEyLYzcWexKxd1gMcTcUOpscy2V5oel+gB2NnTXNPVcjCITq3mAJvinf+w2pexlk2ymTAvpuXrpvMYdjtedSys9/c27Xw5Mt9QhBTIt5EF4LGILIUTRtesSbwLxtRbSL7Srx7BoUS5JsRLYhTJX0dLXgelu80vnECNqPtcg3qrI/yU9F8zt0k7xB35SUpXbINViTKk2nBsZ1DnbIcE6VH+FivCF2JtbFr907xTUvKMdqUGBG/VsvAyGc1I1sykOrmnfSvqiUuiJzL5yX3h8LHAHuKXGh0Ga1psG03VzUpwvom4YQB3ZVws7C+BuYL0j+C3FE3lkq8uw8AyK6M5cvi4XRhYfdVSccW9m6e2i3Vsq+Po4qON5w9P/+ME3INDvf8kI6snJOXnFdNWm2nqZB0bFwhH4Tz33sTv5vLLxDOX6/PaxH04CH7UTAQ9JVI2jLP0mV8L54g8dSRr3Xh316xaCHmH1HYtTCs25OW7mFD7yX362TfXlt/lve+n/YnIWmTvz8xwLZQ+n/gKlpJvowE1klGw657QvqG0UzHx9LKC2K9RDxHyfKWaVkrX3K9DpVUXZLhGjylOP7yv7ELg9wFnAYVRoMpYAqf1jMORkZoiyp0hNYc49D2FwPYIh6nmNXEZM=
